[unix_http_server]
file=/var/run/supervisor.sock
chmod=0700

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisord]
nodaemon=true
logfile=/app/data/logs/supervisord.log
logfile_maxbytes=524288
logfile_backups=1
pidfile=/tmp/supervisord.pid

[program:gpsd]
command=/usr/sbin/gpsd -n %(ENV_GPS_DEVICE)s -F /var/run/gpsd.sock -b %(ENV_GPS_BAUD)s
autostart=true
autorestart=true
stdout_logfile=/app/data/logs/gpsd.log
stdout_logfile_maxbytes=524288
stdout_logfile_backups=1
stderr_logfile=/app/data/logs/gpsd.err
stderr_logfile_maxbytes=524288
stderr_logfile_backups=1

[program:dump1090]
command=/usr/bin/dump1090-fa --device-type rtlsdr --gain 49 --net --write-json /app/data/dump1090 --write-json-every 1 --quiet
autostart=true
autorestart=true
stdout_logfile=/app/data/logs/dump1090.log
stdout_logfile_maxbytes=524288
stdout_logfile_backups=1
stderr_logfile=/app/data/logs/dump1090.err
stderr_logfile_maxbytes=524288
stderr_logfile_backups=1

[program:api]
command=python3 /app/api/server.py
directory=/app
environment=ENABLE_GPS="1"
autostart=true
autorestart=true
stdout_logfile=/app/data/logs/api.log
stdout_logfile_maxbytes=524288
stdout_logfile_backups=1
stderr_logfile=/app/data/logs/api.err
stderr_logfile_maxbytes=524288
stderr_logfile_backups=1

[program:scheduler]
command=python3 /app/api/scheduler.py
directory=/app
autostart=true
autorestart=true
stdout_logfile=/app/data/logs/scheduler.log
stdout_logfile_maxbytes=524288
stdout_logfile_backups=1
stderr_logfile=/app/data/logs/scheduler.err
stderr_logfile_maxbytes=524288
stderr_logfile_backups=1
